---
title: "Directory Tree"
author: "Hochia"
date: "2020/12/30"
output: 
  html_document:
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: false
---

```{css, echo=FALSE}
p {
  font-size: 15px;
}
.red {
  color: rgb(200, 4, 4);
}
h1, h2, h3, h4, h5 {
  color: rgb(8, 107, 90);
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Coding 

<div class='red'>
* Workflow:
    + init.py
    + load_files.py
    + pretreat_images.py
</div>

## cnn/

### cnn_helper_data_process.py {.red}

* retrieve one attribute for two categorical training
* save sequential model and its History object
* load model and History object as DataFrame

### lipstick.py

* CNN models for lipstick attribute
    + With dropout layers

## data/

### model/

#### img_x.npy

Image 128*128

#### img_x_36_26.npy

Generated by Coding/pretreat_images.py

#### img_y.npg

Array of 40 attributes

#### lipstick/

Including *Sequential model (.h5)*, and *History object* as pandas DataFrame in *.pkl* and *.csv* format.

## init.py

Import packages

## load_files.py

Load images file names and csv files

# dataset

This is what TA gave us.

## img_align_celeba/

### img_align_celeba/

There are 202599 images.

## list_attr_celeba.csv

## list_bbox_celeba.csv

## list_eval_partition.csv

## list_landmarks_align_celeba.csv

# plot

Plots related to EDA.
